name: CI

on: ["push"]

jobs:
  build-without-warnings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.*
    - name: Restore dependencies
      run: dotnet restore src/Meditation.sln
    - name: Build
      run: dotnet build src/Meditation.sln --no-restore --no-incremental /warnaserror
      
      
  tests:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.*
    - name: Restore dependencies
      run: dotnet restore src/Meditation.sln
    - name: Build (dotnet)
      run: dotnet build src/Meditation.sln --no-restore --no-incremental /property:WarningLevel=0
    - name: Publish (dotnet AOT)
      run: dotnet publish ./src/Meditation.Bootstrap.Native/Meditation.Bootstrap.Native.csproj -r win-x64
    - name: Test
      run: dotnet test src/Meditation.sln --no-build --verbosity normal