name: CI

on: ["push"]

jobs:
  build-without-warnings:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.*
    - name: Restore dependencies
      run: dotnet restore src/Meditation.sln
    - name: Build
      run: dotnet build src/Meditation.sln --no-restore --no-incremental /warnaserror
      
      
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.*
    - name: Restore dependencies
      run: dotnet restore src/Meditation.UnitTests/Meditation.UnitTests.csproj
    - name: Build (dotnet)
      run: dotnet build src/Meditation.UnitTests/Meditation.UnitTests.csproj --no-restore --no-incremental /property:WarningLevel=0
    - name: Test
      run: dotnet test src/Meditation.UnitTests/Meditation.UnitTests.csproj --no-build --verbosity normal